# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-19 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrent',
            name='origin',
            field=models.CharField(default='Unknown', max_length=1000),
        ),
    ]
